version: "2"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    # networks:
    #   - form_hub_network

  redis:
    image: redis:6.2.5-alpine
    # networks:
    #   - form_hub_network

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
    command: yarn start:docker
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 8000
      REDIS_URL: redis://redis:6379
    # networks:
    #   - form_hub_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   form_hub_network:
#     external: true
